### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character

### ISSUE THREAD

**Issue by Flavien06** [maxkirchoff/google-music-dupe-killer#15]
Hi,
The script dont works, I have this error
 ```
Traceback (most recent call last):
  File "kill-dupes.py", line 96, in <module>
    duplicate_tracks = get_duplicate_tracks(all_tracks_by_album, album_track_duplicate_map)
  File "kill-dupes.py", line 41, in get_duplicate_tracks
    print "Queueing for removal: '" + track['title'] + "' from album '" + track['album'] + "' by '" + track['artist']
  File "C:\Python27\lib\encodings\cp850.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2019' in position 24: character maps to <undefined>
```

**Comment by Flavien06** [comment]
solved with IDLE (Python GUI) : https://github.com/maxkirchoff/google-music-dupe-killer/issues/3

IDLE (Python GUI) → file → open → kill_dupes.py
IDLE (Python GUI) → run → run module
